### ISSUE TITLE
Error with RSS feed (content in trailing section)

### ISSUE THREAD

**Issue by rpodcast** [EmilHvitfeldt/hvitfeldt.me#3]
I recently spun up a self-hosted RSS feed aggregator called [Commafeed](https://www.commafeed.com/#/welcome) and wanted to add your blog's feed in my R collection :star: 

I ran into an XML parsing error (both through the app as well as just trying to open the feed directly in a web browser) with the following message:

> error on line 212 at column 1: Extra content at the end of the document

Firefox gives slightly more information:

> XML Parsing Error: not well-formed
Location: https://emilhvitfeldt.com/blog.xml
Line Number 212, Column 7:

Obviously the site itself is rendering just fine, but something must have happened to the feed.

**Comment by EmilHvitfeldt** [comment]
I'm not quite sure what I did. but deleting and rerender a couple of times did the trick, it should work now https://github.com/EmilHvitfeldt/emilhvitfeldt.com/commit/38e34b912739afb9601965807e08193b615e7f35

**Comment by EmilHvitfeldt** [comment]
thanks for letting me know!

**Comment by rpodcast** [comment]
Works perfectly! And thank you for supporting RSS feeds :pray:
